name: continuos-deployment
run-name: Deploy do App 
on:
    pull_request:
        branches:
            - main
    workflow_dispatch:
jobs:
    deploy:
        name: deploy
        runs-on: ubuntu-lastest

        steps:
                - uses: action/checkout@v4
                  with:
                    fetch-depth: 0

                - name: Docker Login 
                  uses: docker/login-action@v3.4.0
                  with:
                    username: ${{ secrets.DOCKER_USER }}
                    password: ${{ secrets.DOCKER_PASSWORD }}

                - name: Build and push Docker image
                  uses: docker/build-push-action@6.16.0
                  with:
                    context: .
                    file: ./Dockerfile
                    push: true
                    tags: augustosantos17/frontend-devops:latest

                - name: Azure WebApp
                  uses: Azure/webapps-deploy@v3.0.1
                  with:
                    app-name: devclass-frontend-devops
                    publish-profile: ${{ secrets.PUBLISH_PROFILE }}
                    image: augustosantos17/frontend-devops